version: '3'

services:
  nirgen:
    container_name: 'nirgen'
    # command: yarn build
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'

    ports:
      - 8080:80

    environment:
      - CHOKIDAR_USEPOLLING=true
